#ifndef _XPM_ALIEN_H_
#define _XPM_ALIEN_H_

static xpm_row_t const xpm_alien[] = {
    /* columns rows colors chars-per-pixel */
    "32 32 12 1 ",
    "  c None",
    ". c #350F0F",
    "X c #491515",
    "o c #601B1B",
    "O c #601C1C",
    "+ c #7F2424",
    "@ c red",
    "# c #DB575C",
    "$ c #FF4747",
    "% c #FF6868",
    "& c #E07D7F",
    "* c #FFBABC",
    /* pixels */
    "                                ",
    "    *******          *******    ",
    "   **&&&+++*        *+++&&&**   ",
    "  *##   &&++*      *++&&   ##*  ",
    "  #       &oo*    *oo&       #  ",
    "          &oo*    *oo&          ",
    "   ***     &Xo&  &oX&     ***   ",
    "  *+++**   &XXo&&oXX&   **+++*  ",
    " *++&ooo* &ooXXXXXXoo& *ooo&++* ",
    " *+& &oo* &oXXXXXXXXo& *oo& &+* ",
    " *&   &oo*oXXXXXXXXXXo*oo&   &* ",
    " *&   &ooXXXXXXXXXXXXXXoo&   &* ",
    " &&    &oXXOXXXXXXXXOXXo&    && ",
    " #&    &oX.@XOOXXOOX@.Xo&    &# ",
    "  ##  *ooXX.O@$OO$@O.XXoo*  ##  ",
    "   #  *oXOOX.@@..@@.XOOXo*  #   ",
    "    # *o.@$OX..XX..OO$@.o* #    ",
    "       &.@@O$%%OO%%$O@@.&       ",
    "       &o...@$$OO$$@...o&       ",
    "      &oo&o.@@@..@@@.o&oo&      ",
    "     &oo& &o...XX...o& &oo&     ",
    "     &o&  &+ooo&&ooo+&  &o&     ",
    "     #o&    +o&  &o+    &o#     ",
    "      &+#  *+##  ##+*  #+&      ",
    "      &+# *+#      #+* #+&      ",
    "      &+# *#        #* #+&      ",
    "      &+# *#        #* #+&      ",
    "    &&+#  #&&      &&#  #+&&    ",
    "   ####    ##      ##    ####   ",
    "  #         ##    ##         #  ",
    "                                ",
    "                                "
};


static char xpm_row_t const xpm_alien_appearing[] = {
    /* columns rows colors chars-per-pixel */
    "32 32 15 1 ",
    "  c black",
    ". c #210909",
    "X c #350F0F",
    "o c #491515",
    "O c #561919",
    "+ c #601B1B",
    "@ c #601C1C",
    "# c #7F2424",
    "$ c #FF0010",
    "% c #DB575C",
    "& c #FF4747",
    "* c #FF6868",
    "= c #E07D7F",
    "- c #FFBABC",
    "; c None",
    /* pixels */
    ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;",
    ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;",
    ";;;;-;;;;;;;;;;;;;;;;;;;;;;;;;;;",
    ";;;-=--;;;;;;-;;;;;;;;;;;;;;;;;;",
    ";;=;;%#-;;;--#-;;;;;;;;;;;;;;;;;",
    ";;;;;%#-;;-;;%#--;;;;;----;;;;;;",
    ";;;;;;=-;;;;;;%#-;;;;-####-;;;;;",
    ";;;;;;==;;;;;;%+=;;;;=++%#-;;;;;",
    ";;;;;;==;;;;;=++=;;;=++%;%=;;;;;",
    ";;;;;==#=;;;-#++#-;-#+#%;%#-;;;;",
    ";;;;;%++#==.=#+++=.=++=;;;=+-;;;",
    ";;;;;%+++#=X=++++=X=++=;;;;==-;;",
    ";;;;;%++++=O==+++%O%++=..;;;;=;;",
    ";;;;;%%=++= &%%%%oo%%%+==..;;;=;",
    ";;;..XO%%== $$oo@@@o%%%%=OX..;;;",
    ";..XO$----  @@@o**&@OOO%%$OOX..;",
    ";..XO$-###- &**X&&&@--OO%$OO...;",
    ";;;..X=#++= $&&X$$$-##--%OX..;;;",
    ";;;;.-#+++%OX---XX-++++#--..;;;;",
    ";;;;-#+++%%%-##=-O%+++++#-;;;;;;",
    ";;;-#=%%%..%%+#+-%%%%%=++#-;;;;;",
    ";;;=#%;;;;...%++-X...;;=+#-;;;;;",
    ";;=+%;;;;;;;.=+=...;;;;;-#-;;;;;",
    ";;=+%;;;;;;;-++=;;;;;;;;=#=;;;;;",
    ";;;==;;;;;;-+++%;;;;;;;;==;;;;;;",
    ";;;==;;;;;;=+%%;;;;;;;;%#=;;;;;;",
    ";;;;==;;;;=#%;;;;;;;;;;%=;;;;;;;",
    ";;;;;;=;;;=%;;;;;;;;;;;%=;;;;;;;",
    ";;;;;;;;;;=%;;;;;;;;;;;%=;;;;;;;",
    ";;;;;;;;;;=%;;;;;;;;;;;;%%;;;;;;",
    ";;;;;;;;;;;=;;;;;;;;;;;;;;%;;;;;",
    ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"
};


static char xpm_row_t const xpm_alien_dead1[] = {
    /* columns rows colors chars-per-pixel */
    "32 32 12 1 ",
    "  c #350F0F",
    ". c #491515",
    "X c #601B1B",
    "o c #DD0007",
    "O c #FF0400",
    "+ c #FF0008",
    "@ c #DD252B",
    "# c #DB575C",
    "$ c #FF4747",
    "% c #E07D7F",
    "& c #FFBABC",
    "* c None",
    /* pixels */
    "********************************",
    "********************************",
    "********************************",
    "********************************",
    "********************************",
    "********************************",
    "********************************",
    "************&&&****&&&**********",
    "*************@X&**&XX%**********",
    "*************#X&*&  #***********",
    "**********&&**#+*+@#************",
    "*********&@X%*#+*@#*************",
    "********##@@@+@+&%**&&&*********",
    "*************%X@@X&+++#%********",
    "**********&&%X$O@$X@@#**********",
    "*********%X@++O+@ %*************",
    "********% #@@o +o @++&**********",
    "********##***% o.#*@@ &*********",
    "************&X@o%+&*@@X%********",
    "************&++*%++&**##********",
    "************# +**# #************",
    "************##***# #************",
    "*************#****#*************",
    "********************************",
    "********************************",
    "********************************",
    "********************************",
    "********************************",
    "********************************",
    "********************************",
    "********************************",
    "********************************"
};


static char xpm_row_t const xpm_alien_dead2[]  = {
    /* columns rows colors chars-per-pixel */
    "32 32 5 1 ",
    "  c #491515",
    ". c #601B1B",
    "X c #FF0400",
    "o c #DD252B",
    "O c None",
    /* pixels */
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOO  OOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOO .oo. OOOOOOOOOOOOO",
    "OOOOOOOOOOOO oX Xoo OOOOOOOOOOOO",
    "OOOOOOOOOOOO ooXXX. OOOOOOOOOOOO",
    "OOOOOOOOOOOOO .X ooOOOOOOOOOOOOO",
    "OOOOOOOOOOOOO ooo. OOOOOOOOOOOOO",
    "OOOOOOOOOOOOOO   OOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO"
};



static char xpm_row_t const xpm_alien_dead3[] = {
    /* columns rows colors chars-per-pixel */
    "32 32 6 1 ",
    "  c #26191B",
    ". c #513539",
    "X c #9E686E",
    "o c #FFA8B2",
    "O c #FFBFC6",
    "+ c None",
    /* pixels */
    "++++++++++++++++++++++++++++++++",
    "++++++++++++++++++++++++++++++++",
    "++++++++++++++++++++++++++++++++",
    "++++++++++++++++++++++++++++++++",
    "++++++++++++++++++++++++++++++++",
    "++++++++++++++++++++++++++++++++",
    "++++++++++++++++++++++++++++++++",
    "++++++++++++++++++++++++++++++++",
    "++++++++++++++++++++++++++++++++",
    "++++++++++++++++++++++++++++++++",
    "++++++++++++++++++++++++++++++++",
    "++++++++++++++    ++++++++++++++",
    "+++++++++++++ .... +++++++++++++",
    "++++++++++++ .XXXX. ++++++++++++",
    "+++++++++++ .XooooX. +++++++++++",
    "+++++++++++ .XoOOoX. +++++++++++",
    "+++++++++++ .XoOOoX. +++++++++++",
    "+++++++++++ .XooooX. +++++++++++",
    "++++++++++++ .XXXX. ++++++++++++",
    "+++++++++++++ .... +++++++++++++",
    "++++++++++++++    ++++++++++++++",
    "++++++++++++++++++++++++++++++++",
    "++++++++++++++++++++++++++++++++",
    "++++++++++++++++++++++++++++++++",
    "++++++++++++++++++++++++++++++++",
    "++++++++++++++++++++++++++++++++",
    "++++++++++++++++++++++++++++++++",
    "++++++++++++++++++++++++++++++++",
    "++++++++++++++++++++++++++++++++",
    "++++++++++++++++++++++++++++++++",
    "++++++++++++++++++++++++++++++++",
    "++++++++++++++++++++++++++++++++"
};

static char xpm_row_t const xpm_alien_dead4[] = {
    /* columns rows colors chars-per-pixel */
    "32 32 4 1 ",
    "  c #26191B",
    ". c #513539",
    "X c #9E686E",
    "o c None",
    /* pixels */
    "oooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooo",
    "oooooooooooooo    oooooooooooooo",
    "oooooooooooo  ....  oooooooooooo",
    "ooooooooooo ..XXXX.. ooooooooooo",
    "oooooooooo .XX....XX. oooooooooo",
    "oooooooooo .X.    .X. oooooooooo",
    "ooooooooo .X. oooo .X. ooooooooo",
    "ooooooooo .X. oooo .X. ooooooooo",
    "ooooooooo .X. oooo .X. ooooooooo",
    "ooooooooo .X. oooo .X. ooooooooo",
    "oooooooooo .X.    .X. oooooooooo",
    "oooooooooo .XX....XX. oooooooooo",
    "ooooooooooo ..XXXX.. ooooooooooo",
    "oooooooooooo  ....  oooooooooooo",
    "oooooooooooooo    oooooooooooooo",
    "oooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooo"
};

static char xpm_row_t const xpm_alien_dead5[] = {
    /* columns rows colors chars-per-pixel */
    "32 32 3 1 ",
    "  c #26191B",
    ". c #513539",
    "X c None",
    /* pixels */
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXX    XXXXXXXXXXXXXX",
    "XXXXXXXXXXXX  ....  XXXXXXXXXXXX",
    "XXXXXXXXXXX ..    .. XXXXXXXXXXX",
    "XXXXXXXXXX .  XXXX  . XXXXXXXXXX",
    "XXXXXXXXX . XXXXXXXX . XXXXXXXXX",
    "XXXXXXXXX . XXXXXXXX . XXXXXXXXX",
    "XXXXXXXX . XXXXXXXXXX . XXXXXXXX",
    "XXXXXXXX . XXXXXXXXXX . XXXXXXXX",
    "XXXXXXXX . XXXXXXXXXX . XXXXXXXX",
    "XXXXXXXX . XXXXXXXXXX . XXXXXXXX",
    "XXXXXXXXX . XXXXXXXX . XXXXXXXXX",
    "XXXXXXXXX . XXXXXXXX . XXXXXXXXX",
    "XXXXXXXXXX .  XXXX  . XXXXXXXXXX",
    "XXXXXXXXXXX ..    .. XXXXXXXXXXX",
    "XXXXXXXXXXXX  ....  XXXXXXXXXXXX",
    "XXXXXXXXXXXXXX    XXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};




#endif 


