#ifndef _XPM_ALIEN_H_
#define _XPM_ALIEN_H_

static xpm_row_t const xpm_alien_appearing[] = {
  // columns rows colors chars-per-pixel
  "64 64 15 1 ",
  "  c #000000", // black
  ". c #210909",
  "X c #350F0F",
  "o c #491515",
  "O c #561919",
  "+ c #601B1B",
  "@ c #601C1C",
  "# c #7F2424",
  "$ c #FF0010",
  "% c #DB575C",
  "& c #FF4747",
  "* c #FF6868",
  "= c #E07D7F",
  "- c #FFBABC",
  "; c #000000", // None
  // pixels
  ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;",
  ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;",
  ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;",
  ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;",
  ";;;;;;;;--;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;",
  ";;;;;;;;--;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;",
  ";;;;;;--==----;;;;;;;;;;;;--;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;",
  ";;;;;;--==----;;;;;;;;;;;;--;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;",
  ";;;;==;;;;%%##--;;;;;;----##--;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;",
  ";;;;==;;;;%%##--;;;;;;----##--;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;",
  ";;;;;;;;;;%%##--;;;;--;;;;%%##----;;;;;;;;;;--------;;;;;;;;;;;;",
  ";;;;;;;;;;%%##--;;;;--;;;;%%##----;;;;;;;;;;--------;;;;;;;;;;;;",
  ";;;;;;;;;;;;==--;;;;;;;;;;;;%%##--;;;;;;;;--########--;;;;;;;;;;",
  ";;;;;;;;;;;;==--;;;;;;;;;;;;%%##--;;;;;;;;--########--;;;;;;;;;;",
  ";;;;;;;;;;;;====;;;;;;;;;;;;%%++==;;;;;;;;==++++%%##--;;;;;;;;;;",
  ";;;;;;;;;;;;====;;;;;;;;;;;;%%++==;;;;;;;;==++++%%##--;;;;;;;;;;",
  ";;;;;;;;;;;;====;;;;;;;;;;==++++==;;;;;;==++++%%;;%%==;;;;;;;;;;",
  ";;;;;;;;;;;;====;;;;;;;;;;==++++==;;;;;;==++++%%;;%%==;;;;;;;;;;",
  ";;;;;;;;;;====##==;;;;;;--##++++##--;;--##++##%%;;%%##--;;;;;;;;",
  ";;;;;;;;;;====##==;;;;;;--##++++##--;;--##++##%%;;%%##--;;;;;;;;",
  ";;;;;;;;;;%%++++##====..==##++++++==..==++++==;;;;;;==++--;;;;;;",
  ";;;;;;;;;;%%++++##====..==##++++++==..==++++==;;;;;;==++--;;;;;;",
  ";;;;;;;;;;%%++++++##==XX==++++++++==XX==++++==;;;;;;;;====--;;;;",
  ";;;;;;;;;;%%++++++##==XX==++++++++==XX==++++==;;;;;;;;====--;;;;",
  ";;;;;;;;;;%%++++++++==OO====++++++%%OO%%++++==....;;;;;;;;==;;;;",
  ";;;;;;;;;;%%++++++++==OO====++++++%%OO%%++++==....;;;;;;;;==;;;;",
  ";;;;;;;;;;%%%%==++++==  &&%%%%%%%%oooo%%%%%%++====....;;;;;;==;;",
  ";;;;;;;;;;%%%%==++++==  &&%%%%%%%%oooo%%%%%%++====....;;;;;;==;;",
  ";;;;;;....XXOO%%%%====  $$$$oooo@@@@@@oo%%%%%%%%==OOXX....;;;;;;",
  ";;;;;;....XXOO%%%%====  $$$$oooo@@@@@@oo%%%%%%%%==OOXX....;;;;;;",
  ";;....XXOO$$--------    @@@@@@oo****&&@@OOOOOO%%%%$$OOOOXX....;;",
  ";;....XXOO$$--------    @@@@@@oo****&&@@OOOOOO%%%%$$OOOOXX....;;",
  ";;....XXOO$$--######--  &&****XX&&&&&&@@----OOOO%%$$OOOO......;;",
  ";;....XXOO$$--######--  &&****XX&&&&&&@@----OOOO%%$$OOOO......;;",
  ";;;;;;....XX==##++++==  $$&&&&XX$$$$$$--####----%%OOXX....;;;;;;",
  ";;;;;;....XX==##++++==  $$&&&&XX$$$$$$--####----%%OOXX....;;;;;;",
  ";;;;;;;;..--##++++++%%OOXX------XXXX--++++++++##----....;;;;;;;;",
  ";;;;;;;;..--##++++++%%OOXX------XXXX--++++++++##----....;;;;;;;;",
  ";;;;;;;;--##++++++%%%%%%--####==--OO%%++++++++++##--;;;;;;;;;;;;",
  ";;;;;;;;--##++++++%%%%%%--####==--OO%%++++++++++##--;;;;;;;;;;;;",
  ";;;;;;--##==%%%%%%....%%%%++##++--%%%%%%%%%%==++++##--;;;;;;;;;;",
  ";;;;;;--##==%%%%%%....%%%%++##++--%%%%%%%%%%==++++##--;;;;;;;;;;",
  ";;;;;;==##%%;;;;;;;;......%%++++--XX......;;;;==++##--;;;;;;;;;;",
  ";;;;;;==##%%;;;;;;;;......%%++++--XX......;;;;==++##--;;;;;;;;;;",
  ";;;;==++%%;;;;;;;;;;;;;;..==++==......;;;;;;;;;;--##--;;;;;;;;;;",
  ";;;;==++%%;;;;;;;;;;;;;;..==++==......;;;;;;;;;;--##--;;;;;;;;;;",
  ";;;;==++%%;;;;;;;;;;;;;;--++++==;;;;;;;;;;;;;;;;==##==;;;;;;;;;;",
  ";;;;==++%%;;;;;;;;;;;;;;--++++==;;;;;;;;;;;;;;;;==##==;;;;;;;;;;",
  ";;;;;;====;;;;;;;;;;;;--++++++%%;;;;;;;;;;;;;;;;====;;;;;;;;;;;;",
  ";;;;;;====;;;;;;;;;;;;--++++++%%;;;;;;;;;;;;;;;;====;;;;;;;;;;;;",
  ";;;;;;====;;;;;;;;;;;;==++%%%%;;;;;;;;;;;;;;;;%%##==;;;;;;;;;;;;",
  ";;;;;;====;;;;;;;;;;;;==++%%%%;;;;;;;;;;;;;;;;%%##==;;;;;;;;;;;;",
  ";;;;;;;;====;;;;;;;;==##%%;;;;;;;;;;;;;;;;;;;;%%==;;;;;;;;;;;;;;",
  ";;;;;;;;====;;;;;;;;==##%%;;;;;;;;;;;;;;;;;;;;%%==;;;;;;;;;;;;;;",
  ";;;;;;;;;;;;==;;;;;;==%%;;;;;;;;;;;;;;;;;;;;;;%%==;;;;;;;;;;;;;;",
  ";;;;;;;;;;;;==;;;;;;==%%;;;;;;;;;;;;;;;;;;;;;;%%==;;;;;;;;;;;;;;",
  ";;;;;;;;;;;;;;;;;;;;==%%;;;;;;;;;;;;;;;;;;;;;;%%==;;;;;;;;;;;;;;",
  ";;;;;;;;;;;;;;;;;;;;==%%;;;;;;;;;;;;;;;;;;;;;;%%==;;;;;;;;;;;;;;",
  ";;;;;;;;;;;;;;;;;;;;==%%;;;;;;;;;;;;;;;;;;;;;;;;%%%%;;;;;;;;;;;;",
  ";;;;;;;;;;;;;;;;;;;;==%%;;;;;;;;;;;;;;;;;;;;;;;;%%%%;;;;;;;;;;;;",
  ";;;;;;;;;;;;;;;;;;;;;;==;;;;;;;;;;;;;;;;;;;;;;;;;;;;%%;;;;;;;;;;",
  ";;;;;;;;;;;;;;;;;;;;;;==;;;;;;;;;;;;;;;;;;;;;;;;;;;;%%;;;;;;;;;;",
  ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;",
  ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"};

static xpm_row_t const xpm_alien_alive[] = {
  // columns rows colors chars-per-pixel
  "64 64 12 1 ",
  "  c #350F0F",
  ". c #491515",
  "X c #601B1B",
  "o c #601C1C",
  "O c #7F2424",
  "+ c #FF0000", // red
  "@ c #DB575C",
  "# c #FF4747",
  "$ c #FF6868",
  "% c #E07D7F",
  "& c #FFBABC",
  "* c #000000", // None
  // pixels
  "****************************************************************",
  "****************************************************************",
  "********&&&&&&&&&&&&&&********************&&&&&&&&&&&&&&********",
  "********&&&&&&&&&&&&&&********************&&&&&&&&&&&&&&********",
  "******&&&&%%%%%%OOOOOO&&****************&&OOOOOO%%%%%%&&&&******",
  "******&&&&%%%%%%OOOOOO&&****************&&OOOOOO%%%%%%&&&&******",
  "****&&@@@@******%%%%OOOO&&************&&OOOO%%%%******@@@@&&****",
  "****&&@@@@******%%%%OOOO&&************&&OOOO%%%%******@@@@&&****",
  "****@@**************%%XXXX&&********&&XXXX%%**************@@****",
  "****@@**************%%XXXX&&********&&XXXX%%**************@@****",
  "********************%%XXXX&&********&&XXXX%%********************",
  "********************%%XXXX&&********&&XXXX%%********************",
  "******&&&&&&**********%%..XX%%****%%XX..%%**********&&&&&&******",
  "******&&&&&&**********%%..XX%%****%%XX..%%**********&&&&&&******",
  "****&&OOOOOO&&&&******%%....XX%%%%XX....%%******&&&&OOOOOO&&****",
  "****&&OOOOOO&&&&******%%....XX%%%%XX....%%******&&&&OOOOOO&&****",
  "**&&OOOO%%XXXXXX&&**%%XXXX............XXXX%%**&&XXXXXX%%OOOO&&**",
  "**&&OOOO%%XXXXXX&&**%%XXXX............XXXX%%**&&XXXXXX%%OOOO&&**",
  "**&&OO%%**%%XXXX&&**%%XX................XX%%**&&XXXX%%**%%OO&&**",
  "**&&OO%%**%%XXXX&&**%%XX................XX%%**&&XXXX%%**%%OO&&**",
  "**&&%%******%%XXXX&&XX....................XX&&XXXX%%******%%&&**",
  "**&&%%******%%XXXX&&XX....................XX&&XXXX%%******%%&&**",
  "**&&%%******%%XXXX............................XXXX%%******%%&&**",
  "**&&%%******%%XXXX............................XXXX%%******%%&&**",
  "**%%%%********%%XX....oo................oo....XX%%********%%%%**",
  "**%%%%********%%XX....oo................oo....XX%%********%%%%**",
  "**@@%%********%%XX..  ++..oooo....oooo..++  ..XX%%********%%@@**",
  "**@@%%********%%XX..  ++..oooo....oooo..++  ..XX%%********%%@@**",
  "****@@@@****&&XXXX....  oo++##oooo##++oo  ....XXXX&&****@@@@****",
  "****@@@@****&&XXXX....  oo++##oooo##++oo  ....XXXX&&****@@@@****",
  "******@@****&&XX..oooo..  ++++    ++++  ..oooo..XX&&****@@******",
  "******@@****&&XX..oooo..  ++++    ++++  ..oooo..XX&&****@@******",
  "********@@**&&XX  ++##oo..    ....    oooo##++  XX&&**@@********",
  "********@@**&&XX  ++##oo..    ....    oooo##++  XX&&**@@********",
  "**************%%  ++++oo##$$$$oooo$$$$##oo++++  %%**************",
  "**************%%  ++++oo##$$$$oooo$$$$##oo++++  %%**************",
  "**************%%XX      ++####oooo####++      XX%%**************",
  "**************%%XX      ++####oooo####++      XX%%**************",
  "************%%XXXX%%XX  ++++++    ++++++  XX%%XXXX%%************",
  "************%%XXXX%%XX  ++++++    ++++++  XX%%XXXX%%************",
  "**********%%XXXX%%**%%XX      ....      XX%%**%%XXXX%%**********",
  "**********%%XXXX%%**%%XX      ....      XX%%**%%XXXX%%**********",
  "**********%%XX%%****%%OOXXXXXX%%%%XXXXXXOO%%****%%XX%%**********",
  "**********%%XX%%****%%OOXXXXXX%%%%XXXXXXOO%%****%%XX%%**********",
  "**********@@XX%%********OOXX%%****%%XXOO********%%XX@@**********",
  "**********@@XX%%********OOXX%%****%%XXOO********%%XX@@**********",
  "************%%OO@@****&&OO@@@@****@@@@OO&&****@@OO%%************",
  "************%%OO@@****&&OO@@@@****@@@@OO&&****@@OO%%************",
  "************%%OO@@**&&OO@@************@@OO&&**@@OO%%************",
  "************%%OO@@**&&OO@@************@@OO&&**@@OO%%************",
  "************%%OO@@**&&@@****************@@&&**@@OO%%************",
  "************%%OO@@**&&@@****************@@&&**@@OO%%************",
  "************%%OO@@**&&@@****************@@&&**@@OO%%************",
  "************%%OO@@**&&@@****************@@&&**@@OO%%************",
  "********%%%%OO@@****@@%%%%************%%%%@@****@@OO%%%%********",
  "********%%%%OO@@****@@%%%%************%%%%@@****@@OO%%%%********",
  "******@@@@@@@@********@@@@************@@@@********@@@@@@@@******",
  "******@@@@@@@@********@@@@************@@@@********@@@@@@@@******",
  "****@@******************@@@@********@@@@******************@@****",
  "****@@******************@@@@********@@@@******************@@****",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************"};

static xpm_row_t const xpm_alien_dead_1[] = {
  // columns rows colors chars-per-pixel
  "64 64 12 1 ",
  "  c #350F0F",
  ". c #491515",
  "X c #601B1B",
  "o c #DD0007",
  "O c #FF0400",
  "+ c #FF0008",
  "@ c #DD252B",
  "# c #DB575C",
  "$ c #FF4747",
  "% c #E07D7F",
  "& c #FFBABC",
  "* c #000000", // None
  // pixels
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "************************&&&&&&********&&&&&&********************",
  "************************&&&&&&********&&&&&&********************",
  "**************************@@XX&&****&&XXXX%%********************",
  "**************************@@XX&&****&&XXXX%%********************",
  "**************************##XX&&**&&    ##**********************",
  "**************************##XX&&**&&    ##**********************",
  "********************&&&&****##++**++@@##************************",
  "********************&&&&****##++**++@@##************************",
  "******************&&@@XX%%**##++**@@##**************************",
  "******************&&@@XX%%**##++**@@##**************************",
  "****************####@@@@@@++@@++&&%%****&&&&&&******************",
  "****************####@@@@@@++@@++&&%%****&&&&&&******************",
  "**************************%%XX@@@@XX&&++++++##%%****************",
  "**************************%%XX@@@@XX&&++++++##%%****************",
  "********************&&&&%%XX$$OO@@$$XX@@@@##********************",
  "********************&&&&%%XX$$OO@@$$XX@@@@##********************",
  "******************%%XX@@++++OO++@@  %%**************************",
  "******************%%XX@@++++OO++@@  %%**************************",
  "****************%%  ##@@@@oo  ++oo  @@++++&&********************",
  "****************%%  ##@@@@oo  ++oo  @@++++&&********************",
  "****************####******%%  oo..##**@@@@  &&******************",
  "****************####******%%  oo..##**@@@@  &&******************",
  "************************&&XX@@oo%%++&&**@@@@XX%%****************",
  "************************&&XX@@oo%%++&&**@@@@XX%%****************",
  "************************&&++++**%%++++&&****####****************",
  "************************&&++++**%%++++&&****####****************",
  "************************##  ++****##  ##************************",
  "************************##  ++****##  ##************************",
  "************************####******##  ##************************",
  "************************####******##  ##************************",
  "**************************##********##**************************",
  "**************************##********##**************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************",
  "****************************************************************"};

static xpm_row_t const xpm_alien_dead_2[] = {
  // columns rows colors chars-per-pixel
  "64 64 5 1 ",
  "  c #491515",
  ". c #601B1B",
  "X c #FF0400",
  "o c #DD252B",
  "O c #000000",
  // pixels
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOO  ..oooo..  OOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOO  ..oooo..  OOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOO  ooXX  XXoooo  OOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOO  ooXX  XXoooo  OOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOO  ooooXXXXXX..  OOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOO  ooooXXXXXX..  OOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOO  ..XX  ooooOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOO  ..XX  ooooOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOO  oooooo..  OOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOO  oooooo..  OOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOO      OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOO      OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO"};

static xpm_row_t const xpm_alien_dead_3[] = {
  // columns rows colors chars-per-pixel
  "64 64 6 1 ",
  "  c #26191B",
  ". c #513539",
  "X c #9E686E",
  "o c #FFA8B2",
  "O c #FFBFC6",
  "+ c #000000", // None
  // pixels
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++        ++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++        ++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++  ........  ++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++  ........  ++++++++++++++++++++++++++",
  "++++++++++++++++++++++++  ..XXXXXXXX..  ++++++++++++++++++++++++",
  "++++++++++++++++++++++++  ..XXXXXXXX..  ++++++++++++++++++++++++",
  "++++++++++++++++++++++  ..XXooooooooXX..  ++++++++++++++++++++++",
  "++++++++++++++++++++++  ..XXooooooooXX..  ++++++++++++++++++++++",
  "++++++++++++++++++++++  ..XXooOOOOooXX..  ++++++++++++++++++++++",
  "++++++++++++++++++++++  ..XXooOOOOooXX..  ++++++++++++++++++++++",
  "++++++++++++++++++++++  ..XXooOOOOooXX..  ++++++++++++++++++++++",
  "++++++++++++++++++++++  ..XXooOOOOooXX..  ++++++++++++++++++++++",
  "++++++++++++++++++++++  ..XXooooooooXX..  ++++++++++++++++++++++",
  "++++++++++++++++++++++  ..XXooooooooXX..  ++++++++++++++++++++++",
  "++++++++++++++++++++++++  ..XXXXXXXX..  ++++++++++++++++++++++++",
  "++++++++++++++++++++++++  ..XXXXXXXX..  ++++++++++++++++++++++++",
  "++++++++++++++++++++++++++  ........  ++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++  ........  ++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++        ++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++        ++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",
  "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"};

static xpm_row_t const xpm_alien_dead_4[] = {
  // columns rows colors chars-per-pixel
  "64 64 4 1 ",
  "  c #26191B",
  ". c #513539",
  "X c #9E686E",
  "o c #000000", // None
  // pixels
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooo        oooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooo        oooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooo    ........    oooooooooooooooooooooooo",
  "oooooooooooooooooooooooo    ........    oooooooooooooooooooooooo",
  "oooooooooooooooooooooo  ....XXXXXXXX....  oooooooooooooooooooooo",
  "oooooooooooooooooooooo  ....XXXXXXXX....  oooooooooooooooooooooo",
  "oooooooooooooooooooo  ..XXXX........XXXX..  oooooooooooooooooooo",
  "oooooooooooooooooooo  ..XXXX........XXXX..  oooooooooooooooooooo",
  "oooooooooooooooooooo  ..XX..        ..XX..  oooooooooooooooooooo",
  "oooooooooooooooooooo  ..XX..        ..XX..  oooooooooooooooooooo",
  "oooooooooooooooooo  ..XX..  oooooooo  ..XX..  oooooooooooooooooo",
  "oooooooooooooooooo  ..XX..  oooooooo  ..XX..  oooooooooooooooooo",
  "oooooooooooooooooo  ..XX..  oooooooo  ..XX..  oooooooooooooooooo",
  "oooooooooooooooooo  ..XX..  oooooooo  ..XX..  oooooooooooooooooo",
  "oooooooooooooooooo  ..XX..  oooooooo  ..XX..  oooooooooooooooooo",
  "oooooooooooooooooo  ..XX..  oooooooo  ..XX..  oooooooooooooooooo",
  "oooooooooooooooooo  ..XX..  oooooooo  ..XX..  oooooooooooooooooo",
  "oooooooooooooooooo  ..XX..  oooooooo  ..XX..  oooooooooooooooooo",
  "oooooooooooooooooooo  ..XX..        ..XX..  oooooooooooooooooooo",
  "oooooooooooooooooooo  ..XX..        ..XX..  oooooooooooooooooooo",
  "oooooooooooooooooooo  ..XXXX........XXXX..  oooooooooooooooooooo",
  "oooooooooooooooooooo  ..XXXX........XXXX..  oooooooooooooooooooo",
  "oooooooooooooooooooooo  ....XXXXXXXX....  oooooooooooooooooooooo",
  "oooooooooooooooooooooo  ....XXXXXXXX....  oooooooooooooooooooooo",
  "oooooooooooooooooooooooo    ........    oooooooooooooooooooooooo",
  "oooooooooooooooooooooooo    ........    oooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooo        oooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooo        oooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
  "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo"};

static xpm_row_t const xpm_alien_dead_5[] = {
  // columns rows colors chars-per-pixel
  "64 64 3 1 ",
  "  c #26191B",
  ". c #513539",
  "X c #000000", // None
  // pixels
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXX  ....        ....  XXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXX  ....        ....  XXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXX  ..    XXXXXXXX    ..  XXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXX  ..    XXXXXXXX    ..  XXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXX  ..  XXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXX  ..    XXXXXXXX    ..  XXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXX  ..    XXXXXXXX    ..  XXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXX  ....        ....  XXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXX  ....        ....  XXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"};

#endif


