#ifndef _LCOM_VIDEO_CARD_H_
#define _LCOM_VIDEO_CARD_H_

#define VBE_MODE_AH 0x4F
#define VBE_SET_MODE_AL 0x02
#define VBE_GET_MODE_INFO_AL 0x01 
#define VBE_GET_CTRL_INFO_AL 0x00

#define BIOS_SERVICE_VIDEO_CARD 0x10

#endif 


